# Generated by Django 4.2.16 on 2026-01-07 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Policy name/title", max_length=255),
                ),
                (
                    "policy_number",
                    models.CharField(
                        help_text="Unique policy identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed policy description"),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief summary for listings", max_length=500
                    ),
                ),
                (
                    "base_premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base monthly premium amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ZAR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum coverage/benefit amount",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(
                        help_text="Minimum age for eligibility",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "maximum_age",
                    models.PositiveIntegerField(
                        help_text="Maximum age for eligibility",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "waiting_period_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Waiting period in days before coverage starts",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(help_text="Full terms and conditions text"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        help_text="Current approval status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether policy is active and visible to users",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to feature this policy prominently",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when policy was approved",
                        null=True,
                    ),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True,
                        help_text="Policy brochure PDF",
                        null=True,
                        upload_to="policies/brochures/",
                    ),
                ),
                (
                    "application_form",
                    models.FileField(
                        blank=True,
                        help_text="Application form PDF",
                        null=True,
                        upload_to="policies/forms/",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and search",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields specific to organization",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times policy has been viewed"
                    ),
                ),
                (
                    "comparison_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times policy has been compared"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Base Policy",
                "verbose_name_plural": "Base Policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Health, Life, Funeral)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of category name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of this policy category"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or CSS class for UI display",
                        max_length=50,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display categories"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy Category",
                "verbose_name_plural": "Policy Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type name (e.g., Comprehensive, Basic, Premium)",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of type name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Brief description of this policy type"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display types"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this type is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_types",
                        to="policies.policycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Type",
                "verbose_name_plural": "Policy Types",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(help_text="Review title", max_length=255)),
                ("comment", models.TextField(help_text="Review comment")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Whether reviewer actually purchased this policy",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether review has been approved for display",
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who found this review helpful",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Review",
                "verbose_name_plural": "Policy Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyPremiumCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor_name",
                    models.CharField(
                        help_text="Factor affecting premium (e.g., age, gender, smoker)",
                        max_length=100,
                    ),
                ),
                (
                    "factor_value",
                    models.CharField(
                        help_text="Value of the factor (e.g., '18-25', 'male', 'yes')",
                        max_length=100,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier to apply to base premium",
                        max_digits=5,
                    ),
                ),
                (
                    "additional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional amount to add to premium",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this calculation rule"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_calculations",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Premium Calculation",
                "verbose_name_plural": "Policy Premium Calculations",
                "ordering": ["policy", "factor_name", "factor_value"],
            },
        ),
        migrations.CreateModel(
            name="PolicyFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Feature title", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Detailed feature description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or CSS class", max_length=50
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False, help_text="Whether to highlight this feature"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display features"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Feature",
                "verbose_name_plural": "Policy Features",
                "ordering": ["policy", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyExclusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Exclusion title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what is excluded"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display exclusions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Exclusion",
                "verbose_name_plural": "Policy Exclusions",
                "ordering": ["policy", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyEligibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(help_text="Eligibility criterion", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this criterion"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Whether this criterion is mandatory"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display criteria"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_criteria",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Eligibility",
                "verbose_name_plural": "Policy Eligibility Criteria",
                "ordering": ["policy", "display_order", "criterion"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BROCHURE", "Brochure"),
                            ("TERMS", "Terms & Conditions"),
                            ("APPLICATION", "Application Form"),
                            ("CLAIM_FORM", "Claim Form"),
                            ("GUIDE", "User Guide"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                (
                    "file",
                    models.FileField(
                        help_text="Document file", upload_to="policies/documents/"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the document"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether document is publicly accessible",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
                "ordering": ["policy", "document_type", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="policycategory",
            index=models.Index(fields=["slug"], name="policies_po_slug_c204f5_idx"),
        ),
        migrations.AddIndex(
            model_name="policycategory",
            index=models.Index(
                fields=["is_active"], name="policies_po_is_acti_dadde2_idx"
            ),
        ),
        migrations.AddField(
            model_name="basepolicy",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="basepolicy",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="policies.policycategory",
            ),
        ),
        migrations.AddField(
            model_name="basepolicy",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="basepolicy",
            name="policy_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="policies.policytype",
            ),
        ),
        migrations.AddIndex(
            model_name="policytype",
            index=models.Index(
                fields=["category", "slug"], name="policies_po_categor_86d854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policytype",
            index=models.Index(
                fields=["is_active"], name="policies_po_is_acti_646bfd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policytype",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="policyreview",
            index=models.Index(
                fields=["policy", "is_approved"], name="policies_po_policy__d24e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyreview",
            index=models.Index(fields=["rating"], name="policies_po_rating_056938_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="policyreview",
            unique_together={("policy", "user")},
        ),
        migrations.AddIndex(
            model_name="policypremiumcalculation",
            index=models.Index(
                fields=["policy", "is_active"], name="policies_po_policy__a7de29_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policypremiumcalculation",
            unique_together={("policy", "factor_name", "factor_value")},
        ),
        migrations.AddIndex(
            model_name="policyfeature",
            index=models.Index(
                fields=["policy", "is_highlighted"],
                name="policies_po_policy__7976c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policyexclusion",
            index=models.Index(
                fields=["policy"], name="policies_po_policy__9fc575_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyeligibility",
            index=models.Index(
                fields=["policy", "is_mandatory"], name="policies_po_policy__cae530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["policy", "document_type"],
                name="policies_po_policy__3a7799_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["is_public"], name="policies_po_is_publ_c6b338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basepolicy",
            index=models.Index(
                fields=["organization", "is_active"],
                name="policies_ba_organiz_84c7de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basepolicy",
            index=models.Index(
                fields=["category", "policy_type"],
                name="policies_ba_categor_c56bd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basepolicy",
            index=models.Index(
                fields=["approval_status"], name="policies_ba_approva_915625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basepolicy",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="policies_ba_is_feat_c00b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basepolicy",
            index=models.Index(
                fields=["policy_number"], name="policies_ba_policy__9a5097_idx"
            ),
        ),
    ]
