# Generated by Django 6.0 on 2026-01-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_alter_basepolicy_id_alter_policycategory_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Additional feature title", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed additional feature description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or CSS class", max_length=50
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to highlight this additional feature",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to display additional features",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Additional Features",
                "verbose_name_plural": "Additional Features",
                "ordering": ["policy", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Health Policies"),
                            ("FUNERAL", "Funeral Policies"),
                        ],
                        help_text="Type of insurance policy",
                        max_length=20,
                    ),
                ),
                (
                    "annual_limit_per_member",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall annual limit per member per family",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "monthly_household_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly household income requirement",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "in_hospital_benefit",
                    models.BooleanField(
                        blank=True,
                        help_text="With or without in-hospital benefit",
                        null=True,
                    ),
                ),
                (
                    "out_hospital_benefit",
                    models.BooleanField(
                        blank=True,
                        help_text="With or without out of hospital benefits",
                        null=True,
                    ),
                ),
                (
                    "chronic_medication_availability",
                    models.BooleanField(
                        blank=True,
                        help_text="Chronic medication availability",
                        null=True,
                    ),
                ),
                (
                    "cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount for funeral policy",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "marital_status_requirement",
                    models.CharField(
                        blank=True,
                        help_text="Marital status requirement",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gender_requirement",
                    models.CharField(
                        blank=True,
                        help_text="Gender requirement",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "monthly_net_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly net income requirement",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy Features",
                "verbose_name_plural": "Policy Features",
            },
        ),
        migrations.RemoveIndex(
            model_name="policyfeature",
            name="policies_po_policy__7976c7_idx",
        ),
        migrations.AddField(
            model_name="additionalfeatures",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_features",
                to="policies.basepolicy",
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="policy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_features",
                to="policies.basepolicy",
            ),
        ),
        migrations.RemoveField(
            model_name="policyfeature",
            name="policy",
        ),
        migrations.AddIndex(
            model_name="additionalfeatures",
            index=models.Index(
                fields=["policy", "is_highlighted"],
                name="policies_ad_policy__078236_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policyfeatures",
            index=models.Index(
                fields=["insurance_type"], name="policies_po_insuran_bd75f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyfeatures",
            index=models.Index(
                fields=["policy"], name="policies_po_policy__b2942b_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PolicyFeature",
        ),
    ]
