# Generated by Django 4.2.16 on 2026-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_additionalfeatures_policyfeatures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyfeatures",
            name="ambulance_coverage",
            field=models.BooleanField(
                blank=True,
                help_text="Whether ambulance coverage is included",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="annual_limit_per_family",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual limit per family (replaces per member limit)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="currently_on_medical_aid",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the applicant is currently on medical aid",
                null=True,
            ),
        ),
    ]
