# Generated by Django 4.2.16 on 2026-01-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_add_new_policy_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policyfeatures",
            name="monthly_net_income",
        ),
    ]
