# Generated by Django 4.2.16 on 2026-01-21 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0005_remove_deprecated_monthly_net_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rewards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Reward title (e.g., 'Cashback Program', 'Loyalty Discount')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the reward"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("CASHBACK", "Cashback"),
                            ("DISCOUNT", "Discount"),
                            ("BENEFIT", "Additional Benefit"),
                            ("POINTS", "Loyalty Points"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of reward offered",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary value of reward (if applicable)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage value of reward (if applicable)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(
                        blank=True, help_text="Criteria for earning this reward"
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, help_text="Terms and conditions for the reward"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reward is currently active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying rewards"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="Policy this reward is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="policies.basepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "ordering": ["policy", "display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["policy", "is_active"],
                        name="policies_re_policy__c51878_idx",
                    ),
                    models.Index(
                        fields=["reward_type"], name="policies_re_reward__0893a5_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="policies_re_display_7350da_idx"
                    ),
                ],
            },
        ),
    ]
