# Generated by Django 4.2.16 on 2026-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0006_add_rewards_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalfeatures",
            name="coverage_details",
            field=models.TextField(
                blank=True, help_text="Detailed coverage information and descriptions"
            ),
        ),
    ]
