# Generated by Django 4.2.16 on 2026-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0007_add_coverage_details_to_additional_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyfeatures",
            name="monthly_net_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly net income requirement for funeral policy",
                max_digits=10,
                null=True,
            ),
        ),
    ]
