# Generated by Django 4.2.16 on 2026-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0008_add_monthly_net_income_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyfeatures",
            name="annual_limit_family_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10k-50k", "R10,000 - R50,000"),
                    ("50k-100k", "R50,001 - R100,000"),
                    ("100k-250k", "R100,001 - R250,000"),
                    ("250k-500k", "R250,001 - R500,000"),
                    ("500k-1m", "R500,001 - R1,000,000"),
                    ("1m-2m", "R1,000,001 - R2,000,000"),
                    ("2m-5m", "R2,000,001 - R5,000,000"),
                    ("5m-plus", "R5,000,001+"),
                    ("not_sure", "Not sure / Need guidance"),
                ],
                help_text="Annual limit range per family for matching",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="annual_limit_member_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10k-25k", "R10,000 - R25,000"),
                    ("25k-50k", "R25,001 - R50,000"),
                    ("50k-100k", "R50,001 - R100,000"),
                    ("100k-200k", "R100,001 - R200,000"),
                    ("200k-500k", "R200,001 - R500,000"),
                    ("500k-1m", "R500,001 - R1,000,000"),
                    ("1m-2m", "R1,000,001 - R2,000,000"),
                    ("2m-plus", "R2,000,001+"),
                    ("not_sure", "Not sure / Need guidance"),
                ],
                help_text="Annual limit range per member for matching",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="in_hospital_benefit_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_cover", "No hospital cover"),
                    ("basic", "Basic hospital care"),
                    ("moderate", "Moderate hospital care"),
                    ("extensive", "Extensive hospital care"),
                    ("comprehensive", "Comprehensive hospital care"),
                ],
                help_text="Level of in-hospital coverage provided",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="out_hospital_benefit_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_cover", "No out-of-hospital cover"),
                    ("basic_visits", "Basic clinic visits"),
                    ("routine_care", "Routine medical care"),
                    ("extended_care", "Extended medical care"),
                    ("comprehensive_care", "Comprehensive day-to-day care"),
                ],
                help_text="Level of out-of-hospital coverage provided",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyfeatures",
            name="in_hospital_benefit",
            field=models.BooleanField(
                blank=True,
                help_text="With or without in-hospital benefit (legacy field)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyfeatures",
            name="out_hospital_benefit",
            field=models.BooleanField(
                blank=True,
                help_text="With or without out of hospital benefits (legacy field)",
                null=True,
            ),
        ),
    ]
