# Generated by Django 4.2.16 on 2026-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0009_add_benefit_levels_and_ranges"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyfeatures",
            name="claim_payout_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of hours for claim payout (e.g., 48 hours)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="cover_amount_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10k-25k", "R10,000 - R25,000"),
                    ("25k-50k", "R25,001 - R50,000"),
                    ("50k-75k", "R50,001 - R75,000"),
                    ("75k-100k", "R75,001 - R100,000"),
                    ("100k-150k", "R100,001 - R150,000"),
                    ("150k-200k", "R150,001 - R200,000"),
                    ("200k-plus", "R200,001+"),
                ],
                help_text="Cover amount range for matching purposes",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="family_coverage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual Only"),
                    ("spouse", "Main Member + Spouse"),
                    ("nuclear_family", "Nuclear Family (Parents + Children)"),
                    ("extended_family", "Extended Family (Up to 15 members)"),
                ],
                help_text="Type of family coverage offered",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="funeral_service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic Service - Essential arrangements only"),
                    ("standard", "Standard Service - Comprehensive package"),
                    ("premium", "Premium Service - Full luxury service"),
                    ("cash_only", "Cash Payout Only - No managed services"),
                ],
                help_text="Type of funeral service provided",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="grocery_benefit",
            field=models.BooleanField(
                blank=True, help_text="Whether grocery benefit is provided", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="grocery_benefit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount of grocery benefit",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_catering",
            field=models.BooleanField(
                blank=True,
                help_text="Whether catering for mourners is included",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_coffin",
            field=models.BooleanField(
                blank=True,
                help_text="Whether coffin is included in the service",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_flowers",
            field=models.BooleanField(
                blank=True, help_text="Whether flowers are provided", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_memorial_service",
            field=models.BooleanField(
                blank=True, help_text="Whether memorial service is included", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_transport",
            field=models.BooleanField(
                blank=True, help_text="Whether transport/hearse is included", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="includes_venue",
            field=models.BooleanField(
                blank=True, help_text="Whether funeral venue is provided", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="max_family_members",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of family members covered",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="mourning_clothes_benefit",
            field=models.BooleanField(
                blank=True,
                help_text="Whether mourning clothes allowance is provided",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="repatriation_covered",
            field=models.BooleanField(
                blank=True, help_text="Whether repatriation is covered", null=True
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="waiting_period_accidental_death",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No Waiting Period"),
                    ("1_month", "1 Month"),
                    ("3_months", "3 Months"),
                    ("6_months", "6 Months"),
                    ("12_months", "12 Months"),
                ],
                help_text="Waiting period for accidental death coverage",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policyfeatures",
            name="waiting_period_natural_death",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No Waiting Period"),
                    ("1_month", "1 Month"),
                    ("3_months", "3 Months"),
                    ("6_months", "6 Months"),
                    ("12_months", "12 Months"),
                ],
                help_text="Waiting period for natural death coverage",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyfeatures",
            name="gender_requirement",
            field=models.CharField(
                blank=True,
                help_text="Gender requirement (legacy field)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policyfeatures",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("HEALTH", "Health/Medical Insurance"),
                    ("FUNERAL", "Funeral Insurance"),
                ],
                help_text="Type of insurance policy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policyfeatures",
            name="marital_status_requirement",
            field=models.CharField(
                blank=True,
                help_text="Marital status requirement (legacy field)",
                max_length=50,
                null=True,
            ),
        ),
    ]
