# Generated by Django 4.2.16 on 2026-01-07 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthPolicy",
            fields=[
                (
                    "basepolicy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "coverage_level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("STANDARD", "Standard"),
                            ("COMPREHENSIVE", "Comprehensive"),
                            ("PREMIUM", "Premium"),
                        ],
                        default="STANDARD",
                        help_text="Level of health coverage",
                        max_length=20,
                    ),
                ),
                (
                    "hospital_network_type",
                    models.CharField(
                        help_text="Type of hospital network (e.g., Private, Public, Both)",
                        max_length=50,
                    ),
                ),
                (
                    "includes_hospital_cover",
                    models.BooleanField(
                        default=True,
                        help_text="Whether policy includes hospital/inpatient coverage",
                    ),
                ),
                (
                    "includes_outpatient_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether policy includes outpatient/day-to-day coverage",
                    ),
                ),
                (
                    "includes_dental_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether policy includes dental coverage",
                    ),
                ),
                (
                    "includes_optical_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether policy includes optical/vision coverage",
                    ),
                ),
                (
                    "includes_maternity_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether policy includes maternity coverage",
                    ),
                ),
                (
                    "gp_visits_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of GP visits covered per year (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "specialist_visits_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of specialist visits covered per year",
                        null=True,
                    ),
                ),
                (
                    "chronic_medication_covered",
                    models.BooleanField(
                        default=False, help_text="Whether chronic medication is covered"
                    ),
                ),
                (
                    "chronic_conditions_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of chronic conditions covered",
                        null=True,
                    ),
                ),
                (
                    "hospital_days_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of hospital days covered per year (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "private_hospital_room",
                    models.BooleanField(
                        default=False,
                        help_text="Whether private hospital room is included",
                    ),
                ),
                (
                    "icu_cover_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of ICU days covered per year",
                        null=True,
                    ),
                ),
                (
                    "ambulance_cover",
                    models.BooleanField(
                        default=True, help_text="Whether ambulance services are covered"
                    ),
                ),
                (
                    "emergency_room_cover",
                    models.BooleanField(
                        default=True,
                        help_text="Whether emergency room visits are covered",
                    ),
                ),
                (
                    "annual_checkup_covered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether annual health checkup is covered",
                    ),
                ),
                (
                    "vaccinations_covered",
                    models.BooleanField(
                        default=False, help_text="Whether vaccinations are covered"
                    ),
                ),
                (
                    "screening_tests_covered",
                    models.BooleanField(
                        default=False, help_text="Whether screening tests are covered"
                    ),
                ),
                (
                    "prescription_drug_coverage",
                    models.BooleanField(
                        default=True, help_text="Whether prescription drugs are covered"
                    ),
                ),
                (
                    "prescription_annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual limit for prescription drugs",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "copay_gp_visit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Co-payment amount for GP visits",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "copay_specialist",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Co-payment amount for specialist visits",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "annual_deductible",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Annual deductible amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "out_of_pocket_maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum out-of-pocket expenses per year",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mental_health_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether mental health services are covered",
                    ),
                ),
                (
                    "physiotherapy_sessions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of physiotherapy sessions covered per year",
                        null=True,
                    ),
                ),
                (
                    "alternative_medicine_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether alternative medicine is covered",
                    ),
                ),
                (
                    "home_nursing_care",
                    models.BooleanField(
                        default=False, help_text="Whether home nursing care is covered"
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Policy",
                "verbose_name_plural": "Health Policies",
                "ordering": ["-created_at"],
            },
            bases=("policies.basepolicy",),
        ),
        migrations.CreateModel(
            name="HospitalNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        help_text="Name of the hospital/medical facility",
                        max_length=255,
                    ),
                ),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public Hospital"),
                            ("PRIVATE", "Private Hospital"),
                            ("CLINIC", "Clinic"),
                            ("SPECIALIST", "Specialist Center"),
                            ("DAY_CLINIC", "Day Clinic"),
                        ],
                        help_text="Type of medical facility",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the facility")),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state_province",
                    models.CharField(help_text="State or Province", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "emergency_services",
                    models.BooleanField(
                        default=False,
                        help_text="Whether facility has emergency services",
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of medical specialties available",
                    ),
                ),
                (
                    "is_preferred_provider",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a preferred provider (lower copays)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether facility is currently in network",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "health_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_networks",
                        to="health_policies.healthpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Network",
                "verbose_name_plural": "Hospital Networks",
                "ordering": ["city", "hospital_name"],
                "indexes": [
                    models.Index(
                        fields=["health_policy", "city"],
                        name="health_poli_health__1c2329_idx",
                    ),
                    models.Index(
                        fields=["hospital_type"], name="health_poli_hospita_916242_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthPolicyBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital Services"),
                            ("OUTPATIENT", "Outpatient Services"),
                            ("SPECIALIST", "Specialist Services"),
                            ("DENTAL", "Dental Services"),
                            ("OPTICAL", "Optical Services"),
                            ("MATERNITY", "Maternity Services"),
                            ("MENTAL_HEALTH", "Mental Health"),
                            ("PREVENTIVE", "Preventive Care"),
                            ("EMERGENCY", "Emergency Services"),
                            ("OTHER", "Other Services"),
                        ],
                        help_text="Type of health benefit",
                        max_length=20,
                    ),
                ),
                (
                    "benefit_name",
                    models.CharField(help_text="Name of the benefit", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the benefit"),
                ),
                (
                    "coverage_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coverage limit for this benefit (null for unlimited)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frequency_limit",
                    models.CharField(
                        blank=True,
                        help_text="Frequency limit (e.g., 'per year', 'per visit', 'lifetime')",
                        max_length=100,
                    ),
                ),
                (
                    "copay_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Co-payment percentage for this benefit",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "requires_pre_authorization",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this benefit requires pre-authorization",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this benefit is currently active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display this benefit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_benefits",
                        to="health_policies.healthpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Policy Benefit",
                "verbose_name_plural": "Health Policy Benefits",
                "ordering": ["health_policy", "benefit_type", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["health_policy", "benefit_type"],
                        name="health_poli_health__580da8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChronicConditionCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(
                        help_text="Name of the chronic condition", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of coverage for this condition",
                    ),
                ),
                (
                    "medication_covered",
                    models.BooleanField(
                        default=True,
                        help_text="Whether medication for this condition is covered",
                    ),
                ),
                (
                    "annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual coverage limit for this condition",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "specialist_visits_included",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of specialist visits included per year",
                        null=True,
                    ),
                ),
                (
                    "requires_management_program",
                    models.BooleanField(
                        default=False,
                        help_text="Whether patient must enroll in disease management program",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_conditions",
                        to="health_policies.healthpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chronic Condition Coverage",
                "verbose_name_plural": "Chronic Condition Coverage",
                "ordering": ["health_policy", "condition_name"],
                "indexes": [
                    models.Index(
                        fields=["health_policy"], name="health_poli_health__bec0d3_idx"
                    )
                ],
            },
        ),
    ]
