# Generated by Django 4.2.16 on 2026-01-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_policies", "0002_alter_chronicconditioncoverage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chronicconditioncoverage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="healthpolicybenefit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hospitalnetwork",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
