# Generated by Django 4.2.16 on 2026-01-07 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuneralPolicy",
            fields=[
                (
                    "basepolicy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "cover_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual Only"),
                            ("FAMILY", "Family Cover"),
                            ("EXTENDED_FAMILY", "Extended Family"),
                        ],
                        default="INDIVIDUAL",
                        help_text="Type of funeral cover",
                        max_length=20,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("CASH_PAYOUT", "Cash Payout Only"),
                            ("MANAGED_SERVICE", "Managed Funeral Service"),
                            ("HYBRID", "Cash + Services"),
                        ],
                        default="CASH_PAYOUT",
                        help_text="Type of funeral service provided",
                        max_length=20,
                    ),
                ),
                (
                    "main_member_cover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cover amount for main member",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "includes_spouse_cover",
                    models.BooleanField(
                        default=False, help_text="Whether spouse is covered"
                    ),
                ),
                (
                    "spouse_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount for spouse",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "spouse_same_cover",
                    models.BooleanField(
                        default=True,
                        help_text="Whether spouse has same cover as main member",
                    ),
                ),
                (
                    "includes_children_cover",
                    models.BooleanField(
                        default=False, help_text="Whether children are covered"
                    ),
                ),
                (
                    "number_of_children_covered",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of children covered (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "child_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount per child",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "child_minimum_age",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum age for child coverage (usually 0 for stillborn)",
                    ),
                ),
                (
                    "child_maximum_age",
                    models.PositiveIntegerField(
                        default=21, help_text="Maximum age for child coverage"
                    ),
                ),
                (
                    "includes_parents_cover",
                    models.BooleanField(
                        default=False, help_text="Whether parents are covered"
                    ),
                ),
                (
                    "number_of_parents_covered",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of parents covered (typically 2-4)",
                        null=True,
                    ),
                ),
                (
                    "parent_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount per parent",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "includes_in_laws_cover",
                    models.BooleanField(
                        default=False, help_text="Whether parents-in-law are covered"
                    ),
                ),
                (
                    "in_law_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount per parent-in-law",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "includes_extended_family",
                    models.BooleanField(
                        default=False,
                        help_text="Whether extended family members are covered",
                    ),
                ),
                (
                    "extended_family_members",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of extended family members covered",
                        null=True,
                    ),
                ),
                (
                    "extended_family_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cover amount per extended family member",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "natural_death_waiting_period",
                    models.PositiveIntegerField(
                        default=6, help_text="Waiting period for natural death (months)"
                    ),
                ),
                (
                    "accidental_death_waiting_period",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Waiting period for accidental death (months)",
                    ),
                ),
                (
                    "includes_coffin",
                    models.BooleanField(
                        default=False, help_text="Whether coffin is provided"
                    ),
                ),
                (
                    "includes_transport",
                    models.BooleanField(
                        default=False, help_text="Whether transport/hearse is provided"
                    ),
                ),
                (
                    "includes_venue",
                    models.BooleanField(
                        default=False, help_text="Whether funeral venue is provided"
                    ),
                ),
                (
                    "includes_catering",
                    models.BooleanField(
                        default=False, help_text="Whether catering is provided"
                    ),
                ),
                (
                    "includes_tombstone",
                    models.BooleanField(
                        default=False,
                        help_text="Whether tombstone/headstone is provided",
                    ),
                ),
                (
                    "includes_flowers",
                    models.BooleanField(
                        default=False, help_text="Whether flowers are provided"
                    ),
                ),
                (
                    "includes_memorial_service",
                    models.BooleanField(
                        default=False, help_text="Whether memorial service is included"
                    ),
                ),
                (
                    "repatriation_covered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether repatriation to home country/area is covered",
                    ),
                ),
                (
                    "repatriation_distance_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum repatriation distance in kilometers",
                        null=True,
                    ),
                ),
                (
                    "grocery_benefit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether grocery/cash benefit is provided",
                    ),
                ),
                (
                    "grocery_benefit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of grocery benefit",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mourning_clothes_benefit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether mourning clothes allowance is provided",
                    ),
                ),
                (
                    "mourning_clothes_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount for mourning clothes",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "night_vigil_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Whether night vigil expenses are covered",
                    ),
                ),
                (
                    "night_vigil_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount for night vigil expenses",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "documents_required",
                    models.TextField(
                        blank=True, help_text="List of documents required for claims"
                    ),
                ),
                (
                    "claim_payout_days",
                    models.PositiveIntegerField(
                        default=48, help_text="Number of hours for claim payout"
                    ),
                ),
                (
                    "multiple_claims_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of claims allowed per year (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "premium_increase_frequency",
                    models.CharField(
                        default="ANNUAL",
                        help_text="Frequency of premium increases (e.g., 'ANNUAL', 'NEVER')",
                        max_length=50,
                    ),
                ),
                (
                    "premium_increase_method",
                    models.CharField(
                        blank=True,
                        help_text="Method of premium increase (e.g., 'CPI-linked', 'Age-based')",
                        max_length=100,
                    ),
                ),
                (
                    "automatic_cover_increase",
                    models.BooleanField(
                        default=False, help_text="Whether cover automatically increases"
                    ),
                ),
                (
                    "cover_increase_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual cover increase rate (percentage)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Funeral Policy",
                "verbose_name_plural": "Funeral Policies",
                "ordering": ["-created_at"],
            },
            bases=("policies.basepolicy",),
        ),
        migrations.CreateModel(
            name="FuneralServiceProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Name of funeral service provider", max_length=255
                    ),
                ),
                ("address", models.TextField(help_text="Full address of provider")),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state_province",
                    models.CharField(help_text="State or Province", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        help_text="24/7 emergency contact number",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "services_offered",
                    models.JSONField(
                        default=list,
                        help_text="List of services offered by this provider",
                    ),
                ),
                (
                    "coverage_areas",
                    models.JSONField(
                        default=list,
                        help_text="List of areas/regions covered by this provider",
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True, default=list, help_text="Languages spoken by staff"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "operates_24_7",
                    models.BooleanField(
                        default=True, help_text="Whether provider operates 24/7"
                    ),
                ),
                (
                    "is_preferred_provider",
                    models.BooleanField(
                        default=False, help_text="Whether this is a preferred provider"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether provider is currently in network",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funeral_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_providers",
                        to="funeral_policies.funeralpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funeral Service Provider",
                "verbose_name_plural": "Funeral Service Providers",
                "ordering": ["city", "provider_name"],
                "indexes": [
                    models.Index(
                        fields=["funeral_policy", "city"],
                        name="funeral_pol_funeral_53bec4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FuneralPolicyBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash Benefit"),
                            ("SERVICE", "Funeral Service"),
                            ("REPATRIATION", "Repatriation"),
                            ("GROCERY", "Grocery Benefit"),
                            ("TRANSPORT", "Transport"),
                            ("MEMORIAL", "Memorial Service"),
                            ("COUNSELING", "Grief Counseling"),
                            ("LEGAL", "Legal Assistance"),
                            ("OTHER", "Other Benefit"),
                        ],
                        help_text="Type of benefit",
                        max_length=20,
                    ),
                ),
                (
                    "benefit_name",
                    models.CharField(help_text="Name of the benefit", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the benefit"),
                ),
                (
                    "benefit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary value of benefit (if applicable)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(
                        default=True,
                        help_text="Whether benefit is included in base policy",
                    ),
                ),
                (
                    "additional_premium",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional premium if optional",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "waiting_period_months",
                    models.PositiveIntegerField(
                        default=0, help_text="Waiting period for this benefit (months)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether benefit is currently active"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funeral_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_benefits",
                        to="funeral_policies.funeralpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funeral Policy Benefit",
                "verbose_name_plural": "Funeral Policy Benefits",
                "ordering": ["funeral_policy", "display_order", "benefit_name"],
                "indexes": [
                    models.Index(
                        fields=["funeral_policy", "benefit_type"],
                        name="funeral_pol_funeral_211abf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FamilyCoverageTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("MAIN_MEMBER", "Main Member"),
                            ("SPOUSE", "Spouse"),
                            ("CHILD", "Child"),
                            ("PARENT", "Parent"),
                            ("PARENT_IN_LAW", "Parent-in-Law"),
                            ("SIBLING", "Sibling"),
                            ("GRANDPARENT", "Grandparent"),
                            ("GRANDCHILD", "Grandchild"),
                            ("OTHER_RELATIVE", "Other Relative"),
                        ],
                        help_text="Type of family relationship",
                        max_length=20,
                    ),
                ),
                (
                    "cover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cover amount for this relationship",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_members",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of members for this relationship (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum age for this coverage"
                    ),
                ),
                (
                    "maximum_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum age for this coverage (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "waiting_period_months",
                    models.PositiveIntegerField(
                        default=6, help_text="Waiting period for natural death (months)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of coverage for this relationship",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="Whether this coverage is optional"
                    ),
                ),
                (
                    "additional_premium",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional monthly premium for this tier",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funeral_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_tiers",
                        to="funeral_policies.funeralpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Coverage Tier",
                "verbose_name_plural": "Family Coverage Tiers",
                "ordering": ["funeral_policy", "display_order", "relationship_type"],
                "indexes": [
                    models.Index(
                        fields=["funeral_policy"], name="funeral_pol_funeral_181a06_idx"
                    )
                ],
                "unique_together": {("funeral_policy", "relationship_type")},
            },
        ),
        migrations.CreateModel(
            name="ClaimRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DEATH_CERT", "Death Certificate"),
                            ("ID_DOC", "ID Document"),
                            ("POLICE_REPORT", "Police Report"),
                            ("MEDICAL_REPORT", "Medical Report"),
                            ("CLAIM_FORM", "Claim Form"),
                            ("PROOF_REL", "Proof of Relationship"),
                            ("BANK_DETAILS", "Bank Details"),
                            ("BURIAL_ORDER", "Burial Order"),
                            ("OTHER", "Other Document"),
                        ],
                        help_text="Type of required document",
                        max_length=20,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name of required document", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what's required"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Whether document is mandatory"
                    ),
                ),
                (
                    "applies_to_natural_death",
                    models.BooleanField(
                        default=True,
                        help_text="Whether required for natural death claims",
                    ),
                ),
                (
                    "applies_to_accidental_death",
                    models.BooleanField(
                        default=True,
                        help_text="Whether required for accidental death claims",
                    ),
                ),
                (
                    "submission_deadline_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days within which document must be submitted",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funeral_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_requirements",
                        to="funeral_policies.funeralpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Requirement",
                "verbose_name_plural": "Claim Requirements",
                "ordering": ["funeral_policy", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["funeral_policy"], name="funeral_pol_funeral_2f9c14_idx"
                    )
                ],
            },
        ),
    ]
