# Generated by Django 6.0 on 2026-01-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funeral_policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimrequirement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="familycoveragetier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="funeralpolicybenefit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="funeralserviceprovider",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
