# Generated by Django 4.2.16 on 2026-01-07 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the insurance organization",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo (recommended: 400x400px)",
                        null=True,
                        upload_to="organizations/logos/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the organization and its services"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary contact phone number", max_length=20
                    ),
                ),
                (
                    "alternative_phone",
                    models.CharField(
                        blank=True,
                        help_text="Alternative contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Organization website URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, unit, etc.",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state_province",
                    models.CharField(help_text="State or Province", max_length=100),
                ),
                (
                    "postal_code",
                    models.CharField(help_text="Postal/ZIP code", max_length=20),
                ),
                (
                    "country",
                    models.CharField(
                        default="South Africa", help_text="Country", max_length=100
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        help_text="Current verification status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the organization is active on the platform",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when organization was verified",
                        null=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Official business registration number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Insurance license number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "license_expiry_date",
                    models.DateField(help_text="Date when insurance license expires"),
                ),
                (
                    "max_policies",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum number of policies this organization can create",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Commission rate percentage for this organization",
                        max_digits=5,
                    ),
                ),
                (
                    "custom_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom configuration settings (JSON format)",
                    ),
                ),
                (
                    "year_established",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year the organization was established",
                        null=True,
                    ),
                ),
                (
                    "employee_count_range",
                    models.CharField(
                        blank=True,
                        help_text="Employee count range (e.g., '50-100', '100-500')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LICENSE", "Insurance License"),
                            ("REGISTRATION", "Business Registration"),
                            ("TAX_CERT", "Tax Certificate"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other Document"),
                        ],
                        help_text="Type of document",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title or name", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document file (PDF, DOCX, JPG, PNG)",
                        upload_to="organizations/documents/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the document"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, help_text="Date when document was issued", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when document expires (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document has been verified by admin",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Document",
                "verbose_name_plural": "Organization Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Contact"),
                            ("BILLING", "Billing Contact"),
                            ("TECHNICAL", "Technical Contact"),
                            ("CLAIMS", "Claims Contact"),
                            ("SUPPORT", "Support Contact"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, help_text="Job title or position", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as primary contact for the organization",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this contact is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this contact"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Contact",
                "verbose_name_plural": "Organization Contacts",
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_537540_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["verification_status"], name="organizatio_verific_000ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="organizatio_is_acti_1ffc28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationdocument",
            index=models.Index(
                fields=["organization", "document_type"],
                name="organizatio_organiz_b8cb1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationdocument",
            index=models.Index(
                fields=["is_verified"], name="organizatio_is_veri_0a8a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationcontact",
            index=models.Index(
                fields=["organization", "is_primary"],
                name="organizatio_organiz_dfa735_idx",
            ),
        ),
    ]
