# Generated by Django 4.2.16 on 2026-01-07 20:21

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="custom_config",
            field=models.JSONField(
                blank=True,
                default=organizations.models.default_custom_config,
                help_text="Custom configuration settings (JSON format)",
            ),
        ),
    ]
