# Generated by Django 4.2.16 on 2026-01-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuotationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Session identifier (not unique, allows multiple categories per Django session)",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("funeral", "Funeral Insurance"),
                        ],
                        help_text="Insurance category for this session",
                        max_length=20,
                    ),
                ),
                (
                    "user_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Processed criteria from survey responses for quotation matching",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the survey has been completed and quotations generated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expiry time (24 hours from creation)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimpleSurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("funeral", "Funeral Insurance"),
                        ],
                        help_text="Insurance category this question belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question text displayed to users"),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name that maps to quotation criteria",
                        max_length=50,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("select", "Dropdown Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                        ],
                        help_text="Type of input control to display",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available choices for select, radio, or checkbox inputs",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Whether this question must be answered"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        help_text="Order in which questions are displayed"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Simple validation rules (min, max, pattern, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="SimpleSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Session identifier for anonymous users",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("funeral", "Funeral Insurance"),
                        ],
                        help_text="Insurance category for this response",
                        max_length=20,
                    ),
                ),
                (
                    "response_value",
                    models.JSONField(
                        help_text="The user's response (can be string, number, list, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simple_surveys.simplesurveyquestion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="simplesurveyquestion",
            index=models.Index(
                fields=["category", "display_order"],
                name="simple_surv_categor_494f3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplesurveyquestion",
            index=models.Index(
                fields=["category", "is_required"],
                name="simple_surv_categor_5cf270_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="simplesurveyquestion",
            unique_together={("category", "field_name")},
        ),
        migrations.AddIndex(
            model_name="quotationsession",
            index=models.Index(
                fields=["session_key"], name="simple_surv_session_f944bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationsession",
            index=models.Index(
                fields=["category", "is_completed"],
                name="simple_surv_categor_6af484_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quotationsession",
            index=models.Index(
                fields=["expires_at"], name="simple_surv_expires_795590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationsession",
            index=models.Index(
                fields=["created_at"], name="simple_surv_created_089ac6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quotationsession",
            unique_together={("session_key", "category")},
        ),
        migrations.AddIndex(
            model_name="simplesurveyresponse",
            index=models.Index(
                fields=["session_key"], name="simple_surv_session_5f0f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simplesurveyresponse",
            index=models.Index(
                fields=["session_key", "category"],
                name="simple_surv_session_403d16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplesurveyresponse",
            index=models.Index(
                fields=["category", "created_at"], name="simple_surv_categor_84ea71_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="simplesurveyresponse",
            unique_together={("session_key", "question")},
        ),
    ]
