# Generated by Django 6.0 on 2026-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the survey respondent", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the survey respondent", max_length=100
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Date of birth of the survey respondent"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address (optional)", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number (optional)", max_length=20
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Health Policies"),
                            ("FUNERAL", "Funeral Policies"),
                        ],
                        help_text="Type of insurance being surveyed",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preferred overall annual limit per member per family",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "household_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly household income",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "wants_in_hospital_benefit",
                    models.BooleanField(
                        blank=True,
                        help_text="Do you want in-hospital benefits?",
                        null=True,
                    ),
                ),
                (
                    "wants_out_hospital_benefit",
                    models.BooleanField(
                        blank=True,
                        help_text="Do you want out-of-hospital benefits?",
                        null=True,
                    ),
                ),
                (
                    "needs_chronic_medication",
                    models.BooleanField(
                        blank=True,
                        help_text="Do you need chronic medication coverage?",
                        null=True,
                    ),
                ),
                (
                    "preferred_cover_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preferred cover amount for funeral policy",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True, help_text="Marital status", max_length=50, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, help_text="Gender", max_length=20, null=True
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly net income",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Simple Survey",
                "verbose_name_plural": "Simple Surveys",
                "indexes": [
                    models.Index(
                        fields=["insurance_type", "created_at"],
                        name="simple_surv_insuran_32ae93_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="simple_surv_created_473039_idx"
                    ),
                ],
            },
        ),
    ]
