# Generated by Django 4.2.16 on 2026-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_surveys", "0002_simplesurvey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simplesurvey",
            name="net_income",
        ),
        migrations.AddField(
            model_name="simplesurvey",
            name="currently_on_medical_aid",
            field=models.BooleanField(
                blank=True, help_text="Are you currently on medical aid?", null=True
            ),
        ),
        migrations.AddField(
            model_name="simplesurvey",
            name="preferred_annual_limit_per_family",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preferred annual limit per family (replaces per member limit)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simplesurvey",
            name="wants_ambulance_coverage",
            field=models.BooleanField(
                blank=True, help_text="Do you want ambulance coverage?", null=True
            ),
        ),
    ]
