# Generated by Django 4.2.16 on 2026-01-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_surveys", "0006_migrate_binary_responses_to_benefit_levels"),
        ("simple_surveys", "0006_migrate_binary_responses_to_benefit_levels_improved"),
    ]

    operations = []
