# Generated by Django 4.2.16 on 2026-01-07 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comparison", "0001_initial"),
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Section name (e.g., 'Personal Info', 'Coverage Needs')",
                        max_length=100,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The actual question text displayed to users"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text Input"),
                            ("NUMBER", "Number Input"),
                            ("CHOICE", "Single Choice"),
                            ("MULTI_CHOICE", "Multiple Choice"),
                            ("RANGE", "Range/Slider"),
                            ("BOOLEAN", "Yes/No"),
                        ],
                        help_text="Type of question input",
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name that maps to comparison criteria",
                        max_length=100,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available choices for choice-based questions",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules (min/max values, required, etc.)",
                    ),
                ),
                (
                    "weight_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="How much this question affects comparison weighting",
                        max_digits=5,
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Additional help text or explanation for users",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Whether this question must be answered"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display this question"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this question is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Policy category this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_questions",
                        to="policies.policycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Question",
                "verbose_name_plural": "Survey Questions",
                "ordering": ["category", "section", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Description of this survey template"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Template version for tracking changes",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Policy category this template is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_templates",
                        to="policies.policycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Template",
                "verbose_name_plural": "Survey Templates",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserSurveyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_save_responses",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically save survey responses as user progresses",
                    ),
                ),
                (
                    "prefill_from_history",
                    models.BooleanField(
                        default=True,
                        help_text="Pre-fill survey questions based on previous responses",
                    ),
                ),
                (
                    "email_survey_reminders",
                    models.BooleanField(
                        default=False,
                        help_text="Send email reminders for incomplete surveys",
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Number of days to retain survey data (0 = indefinite)",
                    ),
                ),
                (
                    "total_surveys_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of surveys completed by user"
                    ),
                ),
                (
                    "last_survey_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of last completed survey", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User's preferred insurance categories",
                        to="policies.policycategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Survey Profile",
                "verbose_name_plural": "User Survey Profiles",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_value",
                    models.JSONField(
                        help_text="Flexible storage for different response types"
                    ),
                ),
                (
                    "confidence_level",
                    models.IntegerField(
                        default=3,
                        help_text="User's confidence in their answer (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.surveyquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Comparison session this response belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="comparison.comparisonsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
                "ordering": ["session", "question__display_order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_responses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of responses to this question",
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of users who completed this question",
                        max_digits=5,
                    ),
                ),
                (
                    "average_response_time",
                    models.DurationField(
                        blank=True,
                        help_text="Average time users spend on this question",
                        null=True,
                    ),
                ),
                (
                    "skip_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of users who skipped this question",
                        max_digits=5,
                    ),
                ),
                (
                    "most_common_response",
                    models.JSONField(
                        blank=True,
                        help_text="Most frequently given response",
                        null=True,
                    ),
                ),
                (
                    "response_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Distribution of responses for analysis",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        help_text="Question these analytics are for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Analytics",
                "verbose_name_plural": "Survey Analytics",
            },
        ),
        migrations.CreateModel(
            name="SavedSurveyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-defined name for this profile", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this profile"
                    ),
                ),
                (
                    "survey_responses",
                    models.JSONField(
                        default=dict,
                        help_text="Saved survey responses in structured format",
                    ),
                ),
                (
                    "criteria_weights",
                    models.JSONField(
                        default=dict,
                        help_text="Derived criteria weights from responses",
                    ),
                ),
                (
                    "user_profile_data",
                    models.JSONField(
                        default=dict, help_text="Processed user profile data"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default profile for this category",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this profile has been used",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this profile was last used",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Insurance category this profile is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_survey_profiles",
                        to="policies.policycategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this saved profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_survey_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Survey Profile",
                "verbose_name_plural": "Saved Survey Profiles",
            },
        ),
        migrations.CreateModel(
            name="QuestionDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(
                        help_text="Value that triggers the child question"
                    ),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("NOT_EQUALS", "Not Equals"),
                            ("GREATER_THAN", "Greater Than"),
                            ("LESS_THAN", "Less Than"),
                            ("CONTAINS", "Contains"),
                            ("IN_LIST", "In List"),
                        ],
                        default="EQUALS",
                        help_text="Operator to use for condition evaluation",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this dependency rule is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_question",
                    models.ForeignKey(
                        help_text="Question that is shown/hidden based on condition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_dependencies",
                        to="surveys.surveyquestion",
                    ),
                ),
                (
                    "parent_question",
                    models.ForeignKey(
                        help_text="Question that triggers the condition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_dependencies",
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Dependency",
                "verbose_name_plural": "Question Dependencies",
                "ordering": ["parent_question", "child_question"],
            },
        ),
        migrations.CreateModel(
            name="ABTestVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the A/B test", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this test is measuring"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage of traffic to include in this test (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="When to start the test", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="When to end the test", null=True
                    ),
                ),
                (
                    "primary_metric",
                    models.CharField(
                        default="completion_rate",
                        help_text="Primary metric to optimize (completion_rate, response_time, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "minimum_sample_size",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Minimum number of participants needed for statistical significance",
                    ),
                ),
                (
                    "variants_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for different test variants",
                    ),
                ),
                (
                    "participants_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of participants in this test"
                    ),
                ),
                (
                    "results_data",
                    models.JSONField(default=dict, help_text="Aggregated results data"),
                ),
                (
                    "statistical_significance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="P-value for statistical significance",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "winning_variant",
                    models.CharField(
                        blank=True,
                        help_text="Winning variant (if test is completed)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "A/B Test Variant",
                "verbose_name_plural": "A/B Test Variants",
                "indexes": [
                    models.Index(
                        fields=["status", "start_date"],
                        name="surveys_abt_status_846701_idx",
                    ),
                    models.Index(
                        fields=["primary_metric"], name="surveys_abt_primary_adaf1d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ABTestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        help_text="Which variant this participant was assigned",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "response_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total time spent on survey in seconds",
                        null=True,
                    ),
                ),
                (
                    "responses_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions answered"
                    ),
                ),
                (
                    "conversion_achieved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the participant achieved the conversion goal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_test_participations",
                        to="comparison.comparisonsession",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="surveys.abtestvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "A/B Test Participant",
                "verbose_name_plural": "A/B Test Participants",
            },
        ),
        migrations.CreateModel(
            name="TemplateQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this question within the template",
                    ),
                ),
                (
                    "is_required_override",
                    models.BooleanField(
                        blank=True,
                        help_text="Override the question's default required setting",
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_questions",
                        to="surveys.surveyquestion",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_questions",
                        to="surveys.surveytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Question",
                "verbose_name_plural": "Template Questions",
                "ordering": ["template", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["template", "display_order"],
                        name="surveys_tem_templat_3f8f46_idx",
                    )
                ],
                "unique_together": {("template", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="surveytemplate",
            index=models.Index(
                fields=["category", "is_active"], name="surveys_sur_categor_f8d10d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveytemplate",
            unique_together={("category", "name", "version")},
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["session"], name="surveys_sur_session_2705e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["question"], name="surveys_sur_questio_4aed97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["created_at"], name="surveys_sur_created_678deb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveyresponse",
            unique_together={("session", "question")},
        ),
        migrations.AddIndex(
            model_name="surveyquestion",
            index=models.Index(
                fields=["category", "section", "is_active"],
                name="surveys_sur_categor_987720_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyquestion",
            index=models.Index(
                fields=["display_order"], name="surveys_sur_display_5d5813_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveyquestion",
            unique_together={("category", "field_name")},
        ),
        migrations.AddIndex(
            model_name="surveyanalytics",
            index=models.Index(
                fields=["question"], name="surveys_sur_questio_e0639c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyanalytics",
            index=models.Index(
                fields=["completion_rate"], name="surveys_sur_complet_93999f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyanalytics",
            index=models.Index(
                fields=["last_updated"], name="surveys_sur_last_up_79e51c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedsurveyprofile",
            index=models.Index(
                fields=["user", "category"], name="surveys_sav_user_id_4fe6fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedsurveyprofile",
            index=models.Index(
                fields=["user", "is_default"], name="surveys_sav_user_id_b7c35e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedsurveyprofile",
            unique_together={("user", "category", "name")},
        ),
        migrations.AddIndex(
            model_name="questiondependency",
            index=models.Index(
                fields=["parent_question", "is_active"],
                name="surveys_que_parent__126664_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questiondependency",
            index=models.Index(
                fields=["child_question"], name="surveys_que_child_q_b85bbf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questiondependency",
            unique_together={("parent_question", "child_question")},
        ),
        migrations.AddIndex(
            model_name="abtestparticipant",
            index=models.Index(
                fields=["test", "variant"], name="surveys_abt_test_id_741ba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abtestparticipant",
            index=models.Index(
                fields=["started_at"], name="surveys_abt_started_39f29e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="abtestparticipant",
            unique_together={("test", "session")},
        ),
    ]
