# Generated by Django 4.2.16 on 2026-01-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Unique session identifier for anonymous users",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        help_text="Status of the comparison session",
                        max_length=20,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Comparison criteria and user preferences",
                    ),
                ),
                (
                    "match_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Match scores for each policy",
                    ),
                ),
                (
                    "survey_completed",
                    models.BooleanField(
                        default=False, help_text="Whether the survey has been completed"
                    ),
                ),
                (
                    "survey_completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of survey completion",
                        max_digits=5,
                    ),
                ),
                (
                    "survey_responses_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of survey responses submitted"
                    ),
                ),
                (
                    "user_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Processed user profile from survey responses",
                    ),
                ),
                (
                    "fallback_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this session is using fallback comparison",
                    ),
                ),
                (
                    "fallback_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of fallback used (basic, enhanced_basic, partial_personalized, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "fallback_reason",
                    models.TextField(
                        blank=True, help_text="Reason why fallback was triggered"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this session expires", null=True
                    ),
                ),
                (
                    "best_match_policy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Policy determined as best match",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_match_comparisons",
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Policy category being compared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="policies.policycategory",
                    ),
                ),
                (
                    "policies",
                    models.ManyToManyField(
                        help_text="Policies included in this comparison",
                        related_name="comparisons",
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this comparison (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparison Session",
                "verbose_name_plural": "Comparison Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall match score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "criteria_scores",
                    models.JSONField(
                        default=dict, help_text="Scores for individual criteria"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Rank among compared policies (1 = best)"
                    ),
                ),
                (
                    "pros",
                    models.JSONField(
                        default=list, help_text="List of advantages for this policy"
                    ),
                ),
                (
                    "cons",
                    models.JSONField(
                        default=list, help_text="List of disadvantages for this policy"
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of why this policy scored as it did",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="Policy being evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_results",
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Comparison session this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="comparison.comparisonsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparison Result",
                "verbose_name_plural": "Comparison Results",
                "ordering": ["session", "rank"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonCriteria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the criteria", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this criteria evaluates"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Model field name to compare", max_length=100
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=50, help_text="Default weight/importance (0-100)"
                    ),
                ),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("HIGHER_BETTER", "Higher is Better"),
                            ("LOWER_BETTER", "Lower is Better"),
                            ("EXACT_MATCH", "Exact Match"),
                            ("RANGE", "Within Range"),
                            ("BOOLEAN", "Yes/No"),
                        ],
                        help_text="How to compare this criteria",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this criteria must be met"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this criteria is active"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Policy category this criteria applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_templates",
                        to="policies.policycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparison Criteria",
                "verbose_name_plural": "Comparison Criteria",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Profile name", max_length=255)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict, help_text="Saved preferences and criteria weights"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's default profile for this category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Policy category this profile is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="policies.policycategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference Profile",
                "verbose_name_plural": "User Preference Profiles",
                "ordering": ["user", "category", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="comparison__user_id_cb7d3f_idx",
                    )
                ],
                "unique_together": {("user", "category", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="comparisonsession",
            index=models.Index(
                fields=["session_key"], name="comparison__session_c39920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonsession",
            index=models.Index(
                fields=["user", "status"], name="comparison__user_id_24c06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonsession",
            index=models.Index(
                fields=["category", "status"], name="comparison__categor_af53b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonsession",
            index=models.Index(
                fields=["created_at"], name="comparison__created_b7bdf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonresult",
            index=models.Index(
                fields=["session", "rank"], name="comparison__session_fe029f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonresult",
            index=models.Index(
                fields=["policy"], name="comparison__policy__90f8cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comparisonresult",
            unique_together={("session", "policy")},
        ),
        migrations.AddIndex(
            model_name="comparisoncriteria",
            index=models.Index(
                fields=["category", "is_active"], name="comparison__categor_6d444b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comparisoncriteria",
            unique_together={("category", "field_name")},
        ),
    ]
