# Generated by Django 6.0 on 2026-01-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparison", "0002_alter_comparisoncriteria_id_and_more"),
        ("policies", "0003_additionalfeatures_policyfeatures_and_more"),
        ("simple_surveys", "0002_simplesurvey"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_compatibility_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall compatibility score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "feature_match_count",
                    models.PositiveIntegerField(
                        help_text="Number of features that match user preferences"
                    ),
                ),
                (
                    "feature_mismatch_count",
                    models.PositiveIntegerField(
                        help_text="Number of features that don't match user preferences"
                    ),
                ),
                (
                    "feature_scores",
                    models.JSONField(
                        default=dict, help_text="Individual feature scores and analysis"
                    ),
                ),
                (
                    "feature_matches",
                    models.JSONField(
                        default=list,
                        help_text="List of features that match user preferences",
                    ),
                ),
                (
                    "feature_mismatches",
                    models.JSONField(
                        default=list,
                        help_text="List of features that don't match user preferences",
                    ),
                ),
                (
                    "compatibility_rank",
                    models.PositiveIntegerField(
                        help_text="Rank among compared policies (1 = best match)"
                    ),
                ),
                (
                    "recommendation_category",
                    models.CharField(
                        choices=[
                            ("PERFECT_MATCH", "Perfect Match"),
                            ("EXCELLENT_MATCH", "Excellent Match"),
                            ("GOOD_MATCH", "Good Match"),
                            ("PARTIAL_MATCH", "Partial Match"),
                            ("POOR_MATCH", "Poor Match"),
                        ],
                        help_text="Category of recommendation based on compatibility score",
                        max_length=50,
                    ),
                ),
                (
                    "match_explanation",
                    models.TextField(
                        help_text="Human-readable explanation of the match quality"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="Policy being evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_comparison_results",
                        to="policies.basepolicy",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        help_text="SimpleSurvey this result is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_comparison_results",
                        to="simple_surveys.simplesurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Comparison Result",
                "verbose_name_plural": "Feature Comparison Results",
                "ordering": ["survey", "compatibility_rank"],
                "indexes": [
                    models.Index(
                        fields=["survey", "compatibility_rank"],
                        name="comparison__survey__682a23_idx",
                    ),
                    models.Index(
                        fields=["policy"], name="comparison__policy__746fb9_idx"
                    ),
                    models.Index(
                        fields=["overall_compatibility_score"],
                        name="comparison__overall_f1b668_idx",
                    ),
                    models.Index(
                        fields=["recommendation_category"],
                        name="comparison__recomme_2c1ece_idx",
                    ),
                ],
                "unique_together": {("survey", "policy")},
            },
        ),
    ]
